name: docs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - libcxx=9.0.1
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1e
  - pip=20.0.2
  - python=3.8.2
  - python_abi=3.8
  - readline=8.0
  - setuptools=46.1.3
  - sqlite=3.30.1
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - click==7.1.1
    - future==0.18.2
    - jinja2==2.11.1
    - livereload==2.6.1
    - lunr==0.5.6
    - markdown==3.2.1
    - markupsafe==1.1.1
    - mkdocs==1.1
    - mkdocs-material==4.6.3
    - nltk==3.4.5
    - pygments==2.6.1
    - pymdown-extensions==7.0
    - pyyaml==5.3.1
    - six==1.14.0
    - tornado==6.0.4
