squidfunk:
  name: NGeneBio
  description: Creator
  avatar: https://avatars.githubusercontent.com/u/18277785
ngenebio:
  name: ngenebio
  description: Creator
  avatar: https://avatars.githubusercontent.com/u/18277785
