name: documentation
on:
  push:
    branches:
      - deploy

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write

jobs:
  documentation:
    name: Build NgeneBio Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: deploy

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up build cache
        uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-${{ hashFiles('.cache/**') }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install \
            "cairosvg>=2.5" \
            "mkdocs-git-committers-plugin-2<1" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.1" \
            "mkdocs-redirects>=1.0" \
            "mkdocs-extra-sass-plugin" \
            "mkdocs-with-pdf" \
            "livereload" \
            "pillow<10" \
            "mkdocs-git-authors-plugin"

      - name: Build Mkdocs
        run: mkdocs build
        shell: bash

      - name: Create deployment archive file
        run: tar -czvf ngenebio-docs.tar.gz site
        shell: bash
